// <auto-generated/>
#nullable enable
namespace GeneratorFixture;

public static class SnapshotCommandsHostingExtensions
{
    public static global::Spellkit.Hosting.SpellkitHost AddSnapshotModule(this global::Spellkit.Hosting.SpellkitHost host)
    {
        return host.Module("snapshot", module =>
        {
            module.RawCommand("echo", "Echoes text.", "snapshot.read", context =>
            {
                var result = global::GeneratorFixture.SnapshotCommands.Echo(global::Spellkit.Hosting.SpellkitCommandConvert.ToString(context.ExecutionContext, context.RawArgument(0)), global::Spellkit.Hosting.SpellkitCommandConvert.ToInt32(context.ExecutionContext, context.RawArgument(1)));
                return global::Spellkit.Hosting.SpellkitCommandConvert.FromString(result);
            },
            global::Spellkit.Hosting.SpellkitCommandParameter.Required<string>("value"),
            global::Spellkit.Hosting.SpellkitCommandParameter.Optional<int>("count", 2));
            module.RawCommand("Maybe", null, null, context =>
            {
                var result = global::GeneratorFixture.SnapshotCommands.Maybe(context.RawArgument(0) is global::Spellkit.Runtime.Types.SpellkitNil ? default(int?) : global::Spellkit.Hosting.SpellkitCommandConvert.ToInt32(context.ExecutionContext, context.RawArgument(0)));
                return result.HasValue ? global::Spellkit.Hosting.SpellkitCommandConvert.FromInteger(result.Value) : global::Spellkit.Runtime.Types.SpellkitNil.Instance;
            },
            global::Spellkit.Hosting.SpellkitCommandParameter.Required<int?>("value"));
        });
    }
}
