using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;

namespace Spellkit.Generators;

[Generator]
public sealed class SpellkitGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var spellkitTypes = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax { Identifier.ValueText: "SpellkitTypeCodes" },
            static (syntaxContext, cancellationToken) => GetSpellkitClass(syntaxContext, cancellationToken))
            .Where(static type => type is not null);

        context.RegisterSourceOutput(
            spellkitTypes,
            static (productionContext, type) => Emit(productionContext, type!));
    }

    private static INamedTypeSymbol GetSpellkitClass(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        var type = context.SemanticModel.GetDeclaredSymbol(declaration, cancellationToken) as INamedTypeSymbol;

        return type?.ContainingNamespace.ToDisplayString() == "Spellkit" ? type : null!;
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol spellkitClass)
    {
        var types = spellkitClass.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static field => field.IsConst && field.ConstantValue is int)
            .Select(static field => new SpellkitTypeSpec(
                (int)field.ConstantValue!,
                field.Name,
                field.GetAttributes().Any(static attribute =>
                    attribute.AttributeClass?.ToDisplayString() == Types.MixinAttribute)))
            .OrderBy(static type => type.Code)
            .ToImmutableArray();

        context.AddSource("Spellkit.generated.cs", SpellkitRegistryEmitter.Emit(types));
    }
}

internal readonly struct SpellkitTypeSpec
{
    public SpellkitTypeSpec(int code, string name, bool isMixin) =>
        (Code, Name, IsMixin) = (code, name, isMixin);

    public int Code { get; }

    public string Name { get; }

    public bool IsMixin { get; }
}

internal static class SpellkitRegistryEmitter
{
    public static Microsoft.CodeAnalysis.Text.SourceText Emit(ImmutableArray<SpellkitTypeSpec> types)
    {
        var writer = new CodeWriter();
        var publicTypes = types.Where(static type => type.Name != "Interop").ToImmutableArray();

        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("using System;");
        writer.AppendLine("using Spellkit.Runtime.Types;");
        writer.AppendLine();
        writer.AppendLine("namespace Spellkit;");
        writer.AppendLine();
        writer.Block("partial class SpellkitTypeCodes", typeWriter =>
        {
            EmitTypeInitialization(typeWriter, types);
            typeWriter.AppendLine();
            EmitTypeCodeLookup(typeWriter, publicTypes);
            typeWriter.AppendLine();
            EmitTypeNameLookup(typeWriter, types);
            typeWriter.AppendLine();
            EmitMixinLookup(typeWriter, types);
        });

        return writer.ToSourceText();
    }

    private static void EmitTypeInitialization(CodeWriter writer, ImmutableArray<SpellkitTypeSpec> types)
    {
        writer.Block("static partial void GetAllGenerated(FastList<SpellkitTypeInfo> types)", method =>
        {
            method.AppendLine("types.AddRange(");
            method.Indent();
            method.AppendLine("new SpellkitTypeInfo[]");
            method.StartBlock();
            method.AppendLine("null!,");
            foreach (var type in types)
            {
                method.AppendLine($"{GetTypeInitializer(type)},");
            }

            method.EndBlock(",");
            method.AppendLine("0,");
            method.AppendLine($"{types.Length + 1});");
            method.Outdent();
        });
    }

    private static void EmitTypeCodeLookup(CodeWriter writer, ImmutableArray<SpellkitTypeSpec> types)
    {
        writer.Block("static partial void GetTypeCodeByNameGenerated(string name, ref int code)", method =>
        {
            method.AppendLine("code = name switch");
            method.StartBlock();
            foreach (var type in types)
            {
                method.AppendLine($"\"{type.Name}\" => {type.Name},");
            }

            method.AppendLine("_ => default");
            method.EndBlock(";");
        });
    }

    private static void EmitTypeNameLookup(CodeWriter writer, ImmutableArray<SpellkitTypeSpec> types)
    {
        writer.Block("static partial void GetTypeNameByCodeGenerated(int code, ref string name)", method =>
        {
            method.AppendLine("name = code switch");
            method.StartBlock();
            foreach (var type in types)
            {
                method.AppendLine($"{type.Name} => \"{type.Name}\",");
            }

            method.AppendLine("_ => code.ToString()");
            method.EndBlock(";");
        });
    }

    private static void EmitMixinLookup(CodeWriter writer, ImmutableArray<SpellkitTypeSpec> types)
    {
        writer.Block("static partial void GetMixinByCodeGenerated(int code, ref SpellkitTypeInfo name)", method =>
        {
            method.AppendLine("name = code switch");
            method.StartBlock();
            foreach (var type in types.Where(static type => type.IsMixin))
            {
                method.AppendLine($"{type.Name} => Spellkit{type.Name}Mixin.Instance,");
            }

            method.AppendLine("_ => throw new ArgumentException(\"code\")");
            method.EndBlock(";");
        });
    }

    private static string GetTypeInitializer(SpellkitTypeSpec type) => type.Name switch
    {
        "TypeInfo" => "new SpellkitMetaTypeInfo()",
        _ when type.IsMixin => $"Spellkit{type.Name}Mixin.Instance",
        _ => $"new Spellkit{type.Name}TypeInfo()"
    };
}
