param(
    [switch]$Check
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$recipesPath = Join-Path $repoRoot "Docs\Recipes.md"
$recipes = @(
    [pscustomobject]@{
        File = "01-collections.kit"
        Title = "Collections and data transformation"
        Description = "Filters a collection and formats the resulting values. It demonstrates arrays, comprehensions, loops, and string formatting."
    },
    [pscustomobject]@{
        File = "02-patterns.kit"
        Title = "Pattern matching"
        Description = 'Classifies values with `match`, including literal, range, and fallback patterns.'
    },
    [pscustomobject]@{
        File = "03-types-and-traits.kit"
        Title = "Types and traits"
        Description = "Defines a value type and a trait implementation, then uses the resulting method from ordinary script code."
    },
    [pscustomobject]@{
        File = "04-iterators.kit"
        Title = "Iterators"
        Description = 'Declares an iterator function with `yield` and consumes it with `for`.'
    },
    [pscustomobject]@{
        File = "05-exceptions.kit"
        Title = "Exceptions"
        Description = "Throws and catches an application error while keeping the script running."
    }
)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("<!-- Generated by scripts/generate-recipes.ps1. Do not edit directly. -->")
$lines.Add("")
$lines.Add("# Spellkit recipes")
$lines.Add("")
$lines.Add("This page contains small, complete programs that run with the Spellkit console. For a language tour, see the [overview](Overview.md); for syntax details, see the [grammar reference](Grammar.md).")
$lines.Add("")
$lines.Add("Build the Release console once from the repository root:")
$lines.Add("")
$lines.Add('```powershell')
$lines.Add(".\scripts\build-local.ps1 -Configuration Release")
$lines.Add('```')

foreach ($recipe in $recipes)
{
    $sourcePath = Join-Path (Join-Path $repoRoot "Examples\Language") $recipe.File
    $source = (Get-Content -Raw -Encoding UTF8 $sourcePath).TrimEnd()

    $lines.Add("")
    $lines.Add("## " + $recipe.Title)
    $lines.Add("")
    $lines.Add($recipe.Description)
    $lines.Add("")
    $lines.Add('```swift')
    $lines.Add($source)
    $lines.Add('```')
    $lines.Add("")
    $lines.Add("Run it with:")
    $lines.Add("")
    $lines.Add('```powershell')
    $lines.Add(("dotnet .\bin\spk.dll .\Examples\Language\{0} -nologo" -f $recipe.File))
    $lines.Add('```')
    $lines.Add("")
    $lines.Add("Source: [" + $recipe.File + "](../Examples/Language/" + $recipe.File + ")")
}

$lines.Add("")
$lines.Add('The Release smoke test executes every listed recipe. Run `scripts/generate-recipes.ps1 -Check` to verify that this page matches the source files.')
$expected = $lines -join [Environment]::NewLine

if ($Check)
{
    $actual = Get-Content -Raw -Encoding UTF8 $recipesPath
    if ($actual.TrimEnd() -ne $expected.TrimEnd())
    {
        throw "Docs/Recipes.md is out of date. Run scripts/generate-recipes.ps1."
    }

    return
}

$expected | Set-Content -Encoding UTF8 $recipesPath
